### ISSUE TITLE
requires.io badge no longer working

### ISSUE THREAD

**Issue by maarten-ic** [multiscale/muscle3#142]
[requires.io has shut down](http://shiningpanda.com/requires-io-clap-de-fin/), so the badge on the README page is no longer working.

Above page indicates two alternatives to its previous service (omitting the gitlab alternative):
- [snyk](https://snyk.io/)
- [Dependabot](https://github.com/dependabot), integrated within [GitHub](https://github.com/features/security)

Note that `docs/source/devtools.rst` also references requires.io.

**Comment by LourensVeen** [comment]
Another one bites the dust. Oh well, thanks to Olivier and Alexis for their many years of great work.

I can't get any budget to pay snyk, and Dependabot already badgers us anyway, so we should probably just give in to the inevitable and hand over the baton to Microsoft. Vendor lock-in sucks, but I guess you can't beat that kind of accumulation of capital.

**Comment by maarten-ic** [comment]
Note: https://github.com/multiscale/muscle3/blob/develop/docs/source/devtools.rst still references requires.io (lines 26 and 131).
