### ISSUE TITLE
Check consistency of execution_model and resources

### ISSUE THREAD

**Issue by LourensVeen** [multiscale/muscle3#168]
If you specify `openmpi` or `intelmpi` for the `execution_model` but also specify `threads` rather than `mpi_processes`, you should get an error, but you don't.

**Comment by maarten-ic** [comment]
Looks like this is already checked by libymmsl in `Configuration.check_consistency`: https://github.com/multiscale/ymmsl-python/blob/develop/ymmsl/configuration.py#L299

Therefore, fixing #161 should also fix this issue
