### ISSUE TITLE
should_save_final_snapshot has apply_overlay?

### ISSUE THREAD

**Issue by LourensVeen** [multiscale/muscle3#181]
Didn't we decide to remove that option? There is now a flag on `Instance()` to use instead of passing this flag to `reuse_instance()`, and changing that is a small effort when adding support for the checkpointing API. So why is this still here?

**Comment by maarten-ic** [comment]
It was only deprecated in the Python API, so it still exists, but gives you a DeprecationWarning.
The C++ and Fortran APIs don't have InstanceFlags implemented yet, so only allow this syntax.

**Comment by LourensVeen** [comment]
But `should_save_final_snapshot()` is a brand new function, so how can it be deprecated? Shouldn't we have released `should_save_final_snapshot()` without the `apply_overlay` parameter at all?

**Comment by maarten-ic** [comment]
It doesn't have `apply_overlay` on develop: https://github.com/multiscale/muscle3/blob/develop/libmuscle/python/libmuscle/instance.py#L628
Also not in the release: https://github.com/multiscale/muscle3/blob/release-0.6.0/libmuscle/python/libmuscle/instance.py#L628

Are you looking at an older version of the branch?
