### ISSUE TITLE
Trivial: label axes in the plot generated by the tutorials

### ISSUE THREAD

**Issue by djgroen** [multiscale/muscle3#24]
Hi Lourens,

I'm demo'ing MUSCLE3 today, and have a particularly trivial request. Could you label the x and y axes in the plots generated by the diffusion model?

I assume x is concentration and y is time (inverted)?

**Comment by LourensVeen** [comment]
Ha, good question. y is time, yes, and it advances downward, I'm not sure what the quantity is that we're modelling here. I guess reaction-diffusion models usually have some kind of concentration.  @Anech, any comments?
