### ISSUE TITLE
Would it be possible to rotate the x-axis labels?

### ISSUE THREAD

**Issue by DavidPCoster** [multiscale/muscle3#244]
Would it be possible to rotate the x-axis labels?

![instances](https://github.com/multiscale/muscle3/assets/40796322/dbc1177d-d2aa-434b-93b1-f576160bca08)

As can be seen in the attached figure, understanding the x-axis is difficult ...

**Comment by LourensVeen** [comment]
I'm guessing these instances all run at the same time? That would lead to some overlap... :smiley: 

Just kidding, you're right of course, and I think we can get matplotlib to rotate them. Maybe even add a heuristic to only rotate them when needed, although that may get tricky when zooming. Perhaps best to just always print them vertically.

**Comment by DavidPCoster** [comment]
I ended up with adding/changing in plot_instances:

    ax.set_xlabel('Instance')
    ax.tick_params(axis='x', labelrotation = 45)
    for label in ax.xaxis.get_ticklabels():
        label.set_horizontalalignment('right')
    ax.set_ylabel('Total time (s)')
    ax.legend(loc='upper right')
    plt.subplots_adjust(bottom=0.30)

to produce

![instances_45deg](https://github.com/multiscale/muscle3/assets/40796322/6fca9f40-8173-4457-994a-2b8f5ae82886)

**Comment by LourensVeen** [comment]
Ah, that looks nice. Maybe I should also try to sort the instances, at least within the same component, so that they're ordered `fusion_muscle3[0]` to `fusion_muscle3[9]`.

**Comment by DavidPCoster** [comment]
While the sorting would be nice, it is not that important to me since all of the fusion_muscle3's are equivalent in my eyes ...

**Comment by DavidPCoster** [comment]
Pull request created ...

**Comment by LourensVeen** [comment]
Merged #253, thanks!

I'm going to tag this `ready for release` now. I normally leave issues open until the fix has actually been released so that people can use it without extra work. We'll close it when the next release is out.

**Comment by LourensVeen** [comment]
Fix released with 0.7.1, please reopen if you encounter further issues.
