### ISSUE TITLE
Simulation timestamp isn't defined completely clearly

### ISSUE THREAD

**Issue by diregoblin** [multiscale/muscle3#29]
>We’ll initialise our simulation time to the time at which that state is valid, which is contained in the timestamp attribute. This is a float containing the number of seconds since the whole simulation started.

I assume this is simulated seconds, instead of wall clock seconds like in a usual timestamp? It's not completely clear from the docs

**Comment by LourensVeen** [comment]
Yes, it's simulation time, not wallclock time. (Actually, it's whatever you put in there, MUSCLE doesn't use this number itself (yet), but it's intended for implementing timescale overlap, and there you definitely need simulation time.)

And I think it's a double, which is also a floating point number, but it's probably good to make that explicit as well. Will fix, thanks!
