### ISSUE TITLE
pkg-config files for MUSCLE3 would be nice to have

### ISSUE THREAD

**Issue by olivhoenen** [multiscale/muscle3#43]
It would be nice to have templated .pc files generated during the install step, such as one can refer to this for getting compile and link flags. I think this feature would simplify life of c++ and fortran users.

**Comment by LourensVeen** [comment]
Released with version 0.3.1, and there's now an installation test which installs the library and builds the examples against it using pkg-config to detect the settings, to ensure that it works.
