### ISSUE TITLE
Installing guide for C++ version points specifically to ver. 0.2.0

### ISSUE THREAD

**Issue by diregoblin** [multiscale/muscle3#44]
https://muscle3.readthedocs.io/en/develop/installing.html
Specifically, "Downloading MUSCLE 3" shows a specific wget. Maybe it's a good idea to point out that the latest version can be found on Github or even to provide a ``clone`` command there?

**Comment by LourensVeen** [comment]
Well, we don't want people to run the development version. That does need to be updated, or better, tied into the single-source VERSION file so it gets auto-updated on release. Thanks for reporting!

**Comment by diregoblin** [comment]
Well, Github also has the master branch, that should be rather stable? Auto-updated version is also a nice solution.

**Comment by LourensVeen** [comment]
Yes, master always has the last released version, so it's just as stable as the tarball.

**Comment by LourensVeen** [comment]
I've tied it into the single-source version system, so that the documentation will always be in sync with the version it's a part of.

**Comment by LourensVeen** [comment]
Fix released with 0.3.1.
