### ISSUE TITLE
MPI C++ version doesn't build

### ISSUE THREAD

**Issue by diregoblin** [multiscale/muscle3#45]
``libmuscle_mpi.version`` is missing, apparently. I'm attaching the log.
[make_mpi.log](https://github.com/multiscale/muscle3/files/4486506/make_mpi.log)

**Comment by LourensVeen** [comment]
Ah yes, this was mentioned in https://github.com/multiscale/muscle3/issues/38 as well. See https://github.com/multiscale/muscle3/issues/38#issuecomment-613537638.

**Comment by LourensVeen** [comment]
Fix released with 0.3.1.
