### ISSUE TITLE
C++ examples Makefile should link to ymmsl

### ISSUE THREAD

**Issue by LourensVeen** [multiscale/muscle3#59]
C++ code uses the ymmsl library directly, so when running pkgconfig, ymmsl should be specified. It's a dependency for libmuscle, so it works if you only specify libmuscle, but that's not correct. The Makefile for the examples currently only specifies libmuscle, so it should be fixed.

Thanks to @diregoblin for reporting.

**Comment by LourensVeen** [comment]
The build instructions printed on install should also be updated, and probably the installation docs, should check.

**Comment by diregoblin** [comment]
Also, I think ``ymmsl.pc`` is missing from ``muscle3/lib/pkgconfig`` after installing the newest develop version, so it can't actually be included through pkgconfig.

**Comment by LourensVeen** [comment]
And actually, the `libmuscle.py` file adds `-lymmsl`. I don't remember, but I think I may have deliberately used only one file for both libraries, since libmuscle cannot be used without ymmsl, and using the ymmsl library stand-alone in C++ really makes no sense.

On the other hand, it's weird to use `libymmsl` headers and then not link to it explicitly. So it's probably still better design to add a `ymmsl.pc` file, make `libmuscle.pc` privately depend on it rather than specifying `-lymmsl` directly, and tell the user to pass both `libmuscle` and `ymmsl` to pkg-config.

**Comment by LourensVeen** [comment]
Released in 0.3.2.
