### ISSUE TITLE
Spaced out

### ISSUE THREAD

**Issue by LourensVeen** [multiscale/muscle3#66]
I'm writing MUSCLE 3 with a space. Everybody else seems to write MUSCLE3 without a space. We should bow to the inevitable and change it to MUSCLE3 officially. Basically, that just means updating all the documentation to use MUSCLE3-without-a-space instead of MUSCLE 3-with-a-space.

**Comment by djgroen** [comment]
I think it has two reasons actually:
1. To my knowledge, MUSCLE2 was written without a space, so it's consistent.
2. When you put MUSCLE3 in a search query, it won't be contaminated with search results for MUSCLE and MUSCLE2, let alone other things related to MUSCLE :).

**Comment by LourensVeen** [comment]
Yep, I keep getting shirtless men advertising fitness products as well :-). Somebody should use MUSCLE3 to do a multiscale simulation of muscle exercise and recovery and growth just to muddy the waters some more...

**Comment by djgroen** [comment]
@LourensVeen So, will it be MUSCLE3 or MUSCLE 3?

I'm asking because I am currently revising the VECMAtk paper, and would like to use the correct convention ;).

**Comment by LourensVeen** [comment]
Erm, well, in the only official scientific publication about it, there's a space. And currently in the documentation there's a space everywhere. But the documentation will change and future publications will use MUSCLE3. So we could either go with a space, reflecting the current published status, or without one, to be future-proof.

Actually, I think we should go with the space for now, and make the change with the next larger release in a couple months, does that make sense?

**Comment by djgroen** [comment]
Yes, it sounds like clear reasoning to me. :)
