### ISSUE TITLE
Update documentation and examples to use new name for ComputeElements

### ISSUE THREAD

**Issue by msebregts** [multiscale/muscle3#92]
The tutorial (https://muscle3.readthedocs.io/en/latest/tutorial.html) and some of the Python example files:
- docs/source/examples/python/reaction_diffusion.py
- docs/source/examples/python/reaction_diffusion.ymmsl
- docs/source/examples/python/reaction_diffusion_qmc.py

still use `ComputeElement` / `compute_elements`. These should be renamed to `Component` / `components` to reflect changes made in ymmsl-python issue https://github.com/multiscale/ymmsl-python/issues/8

**Comment by LourensVeen** [comment]
Good point. That'll teach me to not release in a hurry :-(. Thanks for reporting, I'll patch it up for the next release.

**Comment by LourensVeen** [comment]
Released in 0.5.0.
